package pullrequest

var fixtures = []PullRequestView{
	{
		ID: 1, Group: "review",
		Title: "Add tracing to auth middleware",
		Repo:  "platform/api-gateway", Num: 4821,
		Author: "carol", Age: 1, CI: "passing",
		Changes: "+184 -23", Checks: "12/12", Comments: 3,
		Blocking: []string{"alex"},
	},
	{
		ID: 2, Group: "review",
		Title: "Refactor session store to use Redis cluster",
		Repo:  "platform/auth", Num: 1102,
		Author: "marco", Age: 2, CI: "passing",
		Changes: "+612 -301", Checks: "11/12", Comments: 7,
		Blocking: []string{"alex", "priya"},
	},
	{
		ID: 3, Group: "review",
		Title: "Bump pg-driver to 12.1.0 (security)",
		Repo:  "platform/api-gateway", Num: 4830,
		Author: "dependabot", Age: 0, CI: "pending",
		Changes: "+12 -12", Checks: "8/12", Comments: 0,
		Blocking: []string{"alex"},
	},
	{
		ID: 4, Group: "review",
		Title: "Add rate-limit headers to public API",
		Repo:  "platform/api-gateway", Num: 4799,
		Author: "sarah", Age: 4, CI: "failing",
		Changes: "+88 -14", Checks: "10/12", Comments: 12,
		Blocking: []string{"alex"},
	},
	{
		ID: 5, Group: "mine",
		Title: "Migrate auth to OIDC",
		Repo:  "platform/auth", Num: 1234,
		Author: "alex", Age: 4, CI: "failing",
		Changes: "+1.2k -428", Checks: "9/12", Comments: 23,
		Blocking:    []string{"bob", "carol"},
		Unread:      true,
		NewActivity: &NewActivity{NewCommits: true, NewComments: 3, NewReviews: 1},
	},
	{
		ID: 6, Group: "mine",
		Title: "RFC: background job retry semantics",
		Repo:  "platform/jobs", Num: 88,
		Author: "alex", Age: 8, CI: "passing", Stale: true,
		Changes: "+0 -0", Checks: "—", Comments: 4,
		Blocking:    []string{"dana"},
		Unread:      true,
		NewActivity: &NewActivity{NewComments: 2},
	},
	{
		ID: 7, Group: "mine",
		Title: "Spike: per-tenant query budgets",
		Repo:  "platform/db", Num: 412,
		Author: "alex", Age: 6, CI: "passing", Stale: true,
		Changes: "+340 -12", Checks: "12/12", Comments: 9,
		Blocking: []string{"priya"},
	},
	{
		ID: 8, Group: "mine",
		Title: "Tidy log redaction rules",
		Repo:  "platform/observability", Num: 901,
		Author: "alex", Age: 1, CI: "passing",
		Changes: "+44 -77", Checks: "12/12", Comments: 1,
		Blocking: []string{},
		Unread:   true,
	},
	{
		ID: 9, Group: "mine",
		Title: "Drop unused feature flag: legacy_signin",
		Repo:  "platform/auth", Num: 1241,
		Author: "alex", Age: 0, CI: "pending",
		Changes: "+8 -134", Checks: "5/12", Comments: 0,
		Blocking: []string{},
	},
	{
		ID: 10, Group: "reviewed",
		Title: "Tighten CSRF check on /admin endpoints",
		Repo:  "platform/auth", Num: 1198,
		Author: "marco", Age: 3, CI: "passing",
		Changes: "+62 -18", Checks: "12/12", Comments: 5,
		Blocking:      []string{},
		Unread:        true,
		NewActivity:   &NewActivity{NewReviews: 1, NewComments: 1},
		ViewerVerdict: VerdictApproved,
	},
	{
		ID: 11, Group: "reviewed",
		Title: "Switch jobs queue to streams API",
		Repo:  "platform/jobs", Num: 90,
		Author: "priya", Age: 2, CI: "passing",
		Changes: "+220 -180", Checks: "12/12", Comments: 14,
		Blocking:      []string{"dana"},
		ViewerVerdict: VerdictChangesRequested,
	},
	{
		ID: 12, Group: "merged",
		Title: "Fix flake in auth_test.py",
		Repo:  "platform/auth", Num: 1230,
		Author: "alex", Age: 1, CI: "passing",
		Changes: "+22 -8", Checks: "12/12", Comments: 2,
		Blocking: []string{}, Merged: "yesterday",
	},
	{
		ID: 13, Group: "merged",
		Title: "Bump go to 1.23.4",
		Repo:  "platform/api-gateway", Num: 4801,
		Author: "alex", Age: 2, CI: "passing",
		Changes: "+4 -4", Checks: "12/12", Comments: 0,
		Blocking: []string{}, Merged: "2d ago",
	},
}
